### ISSUE TITLE
Configurable tokenStore path/DB Support

### ISSUE THREAD

**Issue by Mohron** [nguyenquyhy/DiscordBridge#15]
Hi, I use DiscordBridge on all my sponge servers and I would like to be able to only have my players setup their discord login one time. Currently my only option is to use some OS file system trickery to have the token store in multiple places at once but that only kind of works. It would be better if the location of the JSON file was configurable and allow setting of a regular syncing of the file. Also another good option would be supporting DB software so that the token store could be shared between many servers that way!

**Comment by nguyenquyhy** [comment]
Agree, I'll add support for tokenFilePath and MySQL soon.
