### ISSUE TITLE
Login command does not work with 2FA enabled on accounts

### ISSUE THREAD

**Issue by capybara512** [nguyenquyhy/DiscordBridge#31]
When 2 factor authentication is enabled on Discord accounts the login command to show where messages come from in Discord is nonfunctional -- it acts as if the provided username and password are incorrect. I think a good way to solve this issue would be to prompt the player to ender the 2FA code when logins are rejected due to enhanced account security. 

Furthermore, the README.md says the following:
> Admins and mods can log in to their own Discord account, so that chat messages show under their names in Discord.

I think this makes it especially important to implement a 2FA fix because Discord accounts that hold power (ie. mods and admins) should definitely have 2FA enabled.

**Comment by Mohron** [comment]
@capybara512 have you tried using /discord opt?

**Comment by nguyenquyhy** [comment]
And use latest version of the plugin 😄 . If there is still problem, please let me know to reopen this issue.
