### ISSUE TITLE
%r does not work

### ISSUE THREAD

**Issue by Tencao** [nguyenquyhy/DiscordBridge#40]
%r is suppose to show the highest rank of the person talking, however it outputs this error.

> Console 01/11/2017 23:53:01
> 23:53:01java.util.UnknownFormatConversionException: Conversion = 'r'
> at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691) ~[?:1.8.0_111]
> at java.util.Formatter$FormatSpecifier.(Formatter.java:2720) ~[?:1.8.0_111]
> at java.util.Formatter.parse(Formatter.java:2560) ~[?:1.8.0_111]
> at java.util.Formatter.format(Formatter.java:2501) ~[?:1.8.0_111]
> at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_111]
> at java.lang.String.format(String.java:2940) ~[?:1.8.0_111]
> at com.nguyenquyhy.discordbridge.logics.MessageHandler.discordMessageReceived(MessageHandler.java:49) ~[MessageHandler.class:?]
> at com.nguyenquyhy.discordbridge.logics.LoginHandler$1.lambda$onSuccess$0(LoginHandler.java:191) ~[LoginHandler$1.class:?]
> at de.btobastian.javacord.utils.handler.message.MessageCreateHandler$1.run(MessageCreateHandler.java:66) [MessageCreateHandler$1.class:?]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Mohron** [comment]
@Tencao we need more information than this. Please include what plugin version you are running and a pastebin of your config file. Does this error always happen?

**Comment by Tencao** [comment]
Always happens when a message happens on discord. 

Plugin version - 2.2.0
Sponge version - 2202-5.1.0-BETA-2026

Copy of config - https://paste.ee/r/iXWDO

**Comment by nguyenquyhy** [comment]
Please try the latest 2.3.0 version and let me know if you still get this error 😄 . I don't think %r is available in 2.2.0. The README happens to be updated before I release the 2.3.0 version 😋 .
