### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Shane1199** [nguyenquyhy/DiscordBridge#41]
I've slowly been noticing DiscordBridge not inputting Discord messages to in-game. The only way to solve this was to restart it. But this time around, it froze the server. This paste will expire in 1 month, and I only added the last few hours since it was too much for pastebin. To note, the server had been on for around 48 hours and we have been having performance issues if we don't restart in 24 hrs or sooner.

http://pastebin.com/fRBJbfw6

**Comment by nguyenquyhy** [comment]
I don't see any log for DiscordBridge in the paste. Anyway, please try the latest 2.3.0 version and let me know if you still get this error 😄 .
