### ISSUE TITLE
Discord Roles -> MC Ranks?

### ISSUE THREAD

**Issue by meza** [nguyenquyhy/DiscordBridge#47]
ello.

I've a pretty elaborate setup that links my twitch ranks to my discord roles,and people get all sorts of benefits all around. I was wondering if it would be possible to pipe that through this plugin too?

**Comment by Mohron** [comment]
@meza you're going to need to elaborate. If you mean automatically assigning minecraft roles based on discord roles, I would consider that out of the scope of this plugin but it's ultimately up to @nguyenquyhy. DiscordBridge deals with chat not the permissions service. But if you can provide clarification, maybe we can help!

**Comment by meza** [comment]
I'm not saying you should implement a whole permission system, instead of interface with some common ones.

Since you already have the tie-in to discord and the users, it wouldn't be a stretch to retrieve the users' roles on the discord server. You could possibly leave it open for servers to decide how to implement permissions.

I'm thinking of a config section where you could map `set permission` commands to events of user discord role change.

**Comment by nguyenquyhy** [comment]
Can you explain more on what do you want to do based on those roles? We already have role-based templates, but I am not sure if you have another idea.

**Comment by meza** [comment]
Basically, when I have a "moderators" role on my discord, who are the same people as the moderators on my minecraft servers. I would like to be able to `/lp user <username> switchprimarygroup mods` whenever someone's added to the moderators discord group.

So I'd imagine a config file where I could map Discord roles to minecraft roles and then whenever the user's main role changes, do a 
`/lp user <username> switchprimarygroup <minecraft_role_name>`

**Comment by ghost** [comment]
So, basically like DiscordSrv's role sync
