### ISSUE TITLE
Ignore Minecraft Names

### ISSUE THREAD

**Issue by Magi1053** [nguyenquyhy/DiscordBridge#56]
Using on SpongeForge, there are mods with fake users that I don't want to forward to Discord.

**Comment by Magi1053** [comment]
bump

**Comment by axle2005** [comment]
Can you give an example of this? A mod that sends messages to discord?

**Comment by Magi1053** [comment]
https://mods.curse.com/mc-mods/minecraft/221826-custom-npcs

**Comment by axle2005** [comment]
I can't seem to duplicate this issue with that mod. 

I have spawned an NPC and tried talking to it, messages appear in my chat, but not discord. Additionally I have setup some custom dialogs for the NPC and same thing happens. 

Could you try testing again using [This](https://github.com/axle2005/DiscordBridge/releases/tag/2.4.1) 

If it still is printing to discord, please let me know the steps to repeat this.

**Comment by axle2005** [comment]
Nevermind, I finally found what you were refering too by using scripting.
