### ISSUE TITLE
Unterminated object at line 7 column 4

### ISSUE THREAD

**Issue by EmanYm** [nguyenquyhy/DiscordBridge#60]
I had an error during start up on my console which was quickly eaten up by the line limit.
I checked some settings in the config and reloaded discord bridge.
[The error](https://pastebin.com/rrKx50Zc)

Forge 12.18.3.2281
SpongeForge 5.2.0β2274-Forge 2281
Discord Bridge 2.4.0
For some reason I'm getting PermissionsEx errors in here...
PermissionsEx 2.0β147

I'm wondering if it's the way I renamed the mods, `[MC1.10.2]DiscordBridge[v2.4.0][S].jar`
I noticed `%5BMC1.10.2%5DSpongeForge%5Bv5.2.0Î²2274%5D%5BForge2281%5D%5BS%5D.jar` in the error and searched what the %5B means, [and this is the result](http://stackoverflow.com/questions/9966053/what-does-5b-and-5d-in-post-requests-stand-for).

I can try to rename all of the mods/plugins back to default (without the MC and file version) and see if that does anything.  I doubt it will, because it worked with them named this way previously.

**Comment by Mohron** [comment]
You should really not be using PEX because the plugin dev announced a while back that he will no longer be maintaining it. It is quite far behind  LuckPerms and PermissionsManager. I would recommend that you migrate to an actively developed Permissions plugin.

**Comment by EmanYm** [comment]
After looking into the config and using [an online editor](http://www.jsoneditoronline.org) to figure out what was wrong, I had commas where I shouldn't and didn't have commas where I should.  It's fixed now, and functioning as it should.
I also moved away from PermissionsEx as you suggested, and now use LuckPerms.
