### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Sade66** [nguyenquyhy/DiscordBridge#63]
Hello. There are a few feature I feel are missing from this plugin and I was hoping you would consider adding them (as soon as you can).

They are...

- Typing `.players` in chat brings up a list of online players (Customizable).
- Number of online players shows in channel description and updates every few seconds.
- Channel description shows "Server offline" when server is off.

That's pretty much it. I'm not sure how hard these features would be to implement. If you can add these features, that would be amazing.

Thank you! :)

**Comment by Shane1199** [comment]
I like the first and last ones, not sure how hard it would have to work for the second one.

**Comment by Sade66** [comment]
@Shane1199 It happens with this Bukkit plugin, so I know it's possible.

**Comment by fcpwiz** [comment]
@nguyenquyhy I'd _love_ to see these additions! I hope you add them!

**Comment by axle2005** [comment]
Is feature one supposed to be a Minecraft command, or discord command? @Sade66

**Comment by Sade66** [comment]
@axle2005 THis should be in the DIscord chat, to see who is online in Minecraft.

**Comment by fcpwiz** [comment]
@axle2005 This is great! Thank you for doing this!

Is it possible to make it so in the config we could edit the formatting of these things? (Ex. Change what the channel description says when the servers offline, etc.)

Thanks!

**Comment by fcpwiz** [comment]
@axle2005 I'm trying to compile your fork but I'm getting a compile failure.

https://gist.github.com/fcpwiz/22291105862b81fc5ef77c68ee5e8cbc

**Comment by axle2005** [comment]
Oh.. its apparently missing a class for another discord command, hang on, Ill fix that.

**Comment by fcpwiz** [comment]
@axle2005 Yeah that’d be great! Can you upload it to your release page of your fork?

**Comment by Sade66** [comment]
@axle2005 Now I'm getting the following compile error. 

[](https://gist.github.com/Sade66/f2a58d394e3b0faca06f511205febcb1)

**Comment by axle2005** [comment]
```import com.nguyenquyhy.discordbridge.DiscordBridge;
import com.nguyenquyhy.discordbridge.models.ChannelConfig;
import com.nguyenquyhy.discordbridge.models.ChannelMinecraftConfigCore;
import com.nguyenquyhy.discordbridge.models.GlobalConfig;
import com.nguyenquyhy.discordbridge.utils.ChannelUtil;
import com.nguyenquyhy.discordbridge.utils.TextUtil;```

Okay XD That one makes zero sense... its complaining about an import that isn't there... you sure your trying to compile the most recent commit? 

Nvm, Ill just upload a release to mine as @fcpwiz requested.

**Comment by Sade66** [comment]
Thanks @axle2005! :)

**Comment by Sade66** [comment]
All my requests have been fulfilled in @axle2005's [fork](https://github.com/axle2005/DiscordBridge)!

Thanks! 😄
